/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.presenter.CalculoEstatisticoPresenter;
import com.mycompan.models.DadoCollection;
import com.mycompany.models.importarDados.ImportarCSV;
import com.mycompany.presenter.ImportarDadosPresenter;
import com.mycompany.presenter.VisualizarDadosPresenter;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruanr
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * @return the lblQuantidade
     */
    public javax.swing.JLabel getLblQuantidade() {
        return lblQuantidade;
    }

    /**
     * Creates new form PrincipalGUI
     */
    private DadoCollection dados;
     private DefaultTableModel tmDados;
    
    public PrincipalView() {
        initComponents();
        dados = new DadoCollection();
        setVisible(true);
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        lblQuantidade = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        mbPrincipal = new javax.swing.JMenu();
        miImportarDados = new javax.swing.JMenuItem();
        miCalcularEstatistica = new javax.swing.JMenuItem();
        miVisualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDados);

        lblQuantidade.setText("Quuantidade de dados: N");

        mbPrincipal.setText("Opcoes");

        miImportarDados.setText("Importar dados");
        miImportarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarDadosActionPerformed(evt);
            }
        });
        mbPrincipal.add(miImportarDados);

        miCalcularEstatistica.setText("Calcular estatisticas");
        miCalcularEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularEstatisticaActionPerformed(evt);
            }
        });
        mbPrincipal.add(miCalcularEstatistica);

        miVisualizar.setText("Visualizar estatisticas");
        miVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarActionPerformed(evt);
            }
        });
        mbPrincipal.add(miVisualizar);

        jMenuBar1.add(mbPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)
                        .addComponent(lblQuantidade))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidade)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miImportarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarDadosActionPerformed
       ImportarDadosPresenter presenter = new ImportarDadosPresenter(new ImportarCSV(),dados, this);
      
    }//GEN-LAST:event_miImportarDadosActionPerformed

    private void miCalcularEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularEstatisticaActionPerformed
       CalculoEstatisticoPresenter presenter = new CalculoEstatisticoPresenter(dados, this);
    }//GEN-LAST:event_miCalcularEstatisticaActionPerformed

    private void miVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarActionPerformed
       if(dados.isEmpty()){
            JOptionPane.showMessageDialog(this, "estatísticas não foram calculadas.", "ERROR",JOptionPane.INFORMATION_MESSAGE);
        }else{
            VisualizarDadosPresenter presenter = new VisualizarDadosPresenter(dados);
       }
    }//GEN-LAST:event_miVisualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JMenu mbPrincipal;
    private javax.swing.JMenuItem miCalcularEstatistica;
    private javax.swing.JMenuItem miImportarDados;
    private javax.swing.JMenuItem miVisualizar;
    private javax.swing.JTable tblDados;
    // End of variables declaration//GEN-END:variables

    /**
     * @param lblQuantidade the lblQuantidade to set
     */
    public void setLblQuantidade(javax.swing.JLabel lblQuantidade) {
        this.lblQuantidade = lblQuantidade;
    }

    /**
     * @return the tblDados
     */
    public javax.swing.JTable getTblDados() {
        return tblDados;
    }

    /**
     * @param tblDados the tblDados to set
     */
    public void setTblDados(javax.swing.JTable tblDados) {
        this.tblDados = tblDados;
    }
}
